%% ===== Параметры экспорта =====
W = 16;                          % Coefficient_Width
outfile = 'fir_decim10_hex.coe';

% Масштабируем на полный signed 16-bit диапазон.
% Это меняет только общий коэффициент усиления, но не форму АЧХ.
peak = max(abs(coeff));
scale = (2^(W-1)-1) / peak;

coeff_int = round(coeff * scale);

% Ограничение диапазона signed 16-bit
coeff_int(coeff_int >  2^(W-1)-1) =  2^(W-1)-1;
coeff_int(coeff_int < -2^(W-1)  ) = -2^(W-1);

% Перевод в two's complement беззнаковое представление
coeff_u = mod(coeff_int, 2^W);

% В hex с фиксированной шириной
hex_digits = W/4;  % для 16 бит = 4 hex символа
coeff_hex = upper(dec2hex(coeff_u, hex_digits));

%% ===== Запись .coe файла в стиле MATLAB/Core Generator =====
fid = fopen(outfile, 'w');
if fid == -1
    error('Не удалось открыть файл %s для записи', outfile);
end

fprintf(fid, '; XILINX CORE Generator(tm) Distributed Arithmetic FIR filter coefficient (.COE) File\n');
fprintf(fid, '; Generated by MATLAB script\n');
fprintf(fid, '; Generated on: %s\n', datestr(now));
fprintf(fid, 'Radix = 16;\n');
fprintf(fid, 'Coefficient_Width = %d;\n', W);
fprintf(fid, 'CoefData = ');

for k = 1:length(coeff_hex)
    if k < length(coeff_hex)
        fprintf(fid, '%s,\n', coeff_hex(k,:));
    else
        fprintf(fid, '%s;\n', coeff_hex(k,:));
    end
end

fclose(fid);

%% ===== Немного информации =====
fprintf('Файл создан: %s\n', outfile);
fprintf('Макс |coeff| = %.12f\n', peak);
fprintf('Scale factor = %.6f\n', scale);
fprintf('Первые 10 integer coeff = \n');
disp(coeff_int(1:min(10,end)));
fprintf('Первые 10 hex coeff = \n');
disp(coeff_hex(1:min(10,end), :));