# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cic_compiler_3_0/fm_demod2_inst_9_cic_compiler_3_0.xci
# IP: The module: 'fm_demod2_inst_9_cic_compiler_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cic_compiler_3_0/fm_demod2_inst_9_cic_compiler_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_demod2_inst_9_cic_compiler_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cic_compiler_3_0/fm_demod2_inst_9_cic_compiler_3_0.xci
# IP: The module: 'fm_demod2_inst_9_cic_compiler_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cic_compiler_3_0/fm_demod2_inst_9_cic_compiler_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_demod2_inst_9_cic_compiler_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
