# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0.xci
# IP: The module: 'packer_udp2_inst_2_fifo_generator_audio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'packer_udp2_inst_2_fifo_generator_audio_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'packer_udp2_inst_2_fifo_generator_audio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'packer_udp2_inst_2_fifo_generator_audio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0.xci
# IP: The module: 'packer_udp2_inst_2_fifo_generator_audio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'packer_udp2_inst_2_fifo_generator_audio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'packer_udp2_inst_2_fifo_generator_audio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'packer_udp2_inst_2_fifo_generator_audio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
