set_property PACKAGE_PIN K17 [get_ports sys_clk_50M]
set_property PACKAGE_PIN M19 [get_ports sys_rst_n]

#set_property PACKAGE_PIN U15 [get_ports {dac_data[0]}]
#set_property PACKAGE_PIN V15 [get_ports {dac_data[1]}]
#set_property PACKAGE_PIN W15 [get_ports {dac_data[2]}]
#set_property PACKAGE_PIN V17 [get_ports {dac_data[3]}]
#set_property PACKAGE_PIN U17 [get_ports {dac_data[4]}]
#set_property PACKAGE_PIN Y18 [get_ports {dac_data[5]}]
#set_property PACKAGE_PIN V18 [get_ports {dac_data[6]}]
#set_property PACKAGE_PIN Y19 [get_ports {dac_data[7]}]
#set_property PACKAGE_PIN W18 [get_ports {dac_data[8]}]
#set_property PACKAGE_PIN W19 [get_ports {dac_data[9]}]
#set_property PACKAGE_PIN U19 [get_ports {dac_data[10]}]
#set_property PACKAGE_PIN N17 [get_ports {dac_data[11]}]
#set_property PACKAGE_PIN U14 [get_ports {dac_data[12]}]
#set_property PACKAGE_PIN W14 [get_ports {dac_data[13]}]
#set_property PACKAGE_PIN Y14 [get_ports {dac_data[14]}]
#set_property PACKAGE_PIN P16 [get_ports {dac_data[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_50M]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

#set_property PACKAGE_PIN P15 [get_ports dac_dco]
#set_property IOSTANDARD LVCMOS33 [get_ports dac_dco]

set_property PACKAGE_PIN N20 [get_ports {adc_dai[0]}]
set_property PACKAGE_PIN N18 [get_ports {adc_dai[2]}]
set_property PACKAGE_PIN P18 [get_ports {adc_dai[4]}]
set_property PACKAGE_PIN P19 [get_ports {adc_dai[6]}]
set_property PACKAGE_PIN R18 [get_ports {adc_dai[8]}]
set_property PACKAGE_PIN W16 [get_ports {adc_dai[10]}]
set_property PACKAGE_PIN T16 [get_ports {adc_dai[12]}]
set_property PACKAGE_PIN R16 [get_ports {adc_dai[14]}]
set_property PACKAGE_PIN T20 [get_ports {adc_dai[1]}]
set_property PACKAGE_PIN U20 [get_ports {adc_dai[3]}]
set_property PACKAGE_PIN V20 [get_ports {adc_dai[5]}]
set_property PACKAGE_PIN W20 [get_ports {adc_dai[7]}]
set_property PACKAGE_PIN R17 [get_ports {adc_dai[9]}]
set_property PACKAGE_PIN T17 [get_ports {adc_dai[11]}]
set_property PACKAGE_PIN U18 [get_ports {adc_dai[13]}]
set_property PACKAGE_PIN V16 [get_ports {adc_dai[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[0]}]

#create_clock -period 5.000 -name dac_dco -waveform {0.000 2.500} [get_nets dac_dco]
#create_clock -period 7.692 -name adc_dco -waveform {0.000 3.846} [get_nets adc_dco]

set_property PACKAGE_PIN P20 [get_ports adc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]
#set ADC_R_CLK [get_clocks -regexp {.*clk_ADC_R.*}]
#set_input_delay -clock $ADC_R_CLK -min 4.100 [get_ports {adc_dai[*]}]
#set_input_delay -clock $ADC_R_CLK -max 6.800 [get_ports {adc_dai[*]}]
# Теперь отдельно для [14] (пример: сдвинули окно на -0.3нс)
#set_input_delay -clock $ADC_R_CLK -min 2.800 [get_ports adc_dai[14]]
#set_input_delay -clock $ADC_R_CLK -max 6.500 [get_ports adc_dai[14]]



#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[3]/C}] -to [get_pins U_max5885/U_sin_sweep/sweep_en_reg/D]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[3]/C}] -to [get_pins {U_max5885/U_sin_sweep/STATE_reg[3]/D}]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[3]/C}] -to [get_pins {U_max5885/U_sin_sweep/STATE_reg[2]/D}]

#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[26]_P/CE}]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[23]_P/CE}]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[46]_P/CE}]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[24]_P/CE}]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[2]_P/CE}]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[21]_P/CE}]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[43]_P/CE}]
#set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[22]_P/CE}]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets dac_dco_OBUF]

#set_property PACKAGE_PIN M20 [get_ports key_start]
#set_property PACKAGE_PIN M19 [get_ports key_stop]
#set_property IOSTANDARD LVCMOS33 [get_ports key_start]
#set_property IOSTANDARD LVCMOS33 [get_ports key_stop]


#set_property PACKAGE_PIN N27 [get_ports hdmi_cec]
#set_property PACKAGE_PIN N26 [get_ports hdmi_hdp]
#set_property PACKAGE_PIN U21 [get_ports hdmi_scl]
#set_property PACKAGE_PIN V21 [get_ports hdmi_sda]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_cec]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hdp]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]
#set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_en]
#set_property PACKAGE_PIN H18 [get_ports hdmi_out_en]

#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d1[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d1[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d2[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d2[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d0[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d0[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_clk[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {hdmi_clk[0]}]
#set_property PACKAGE_PIN D19 [get_ports {hdmi_d0[1]}]
#set_property PACKAGE_PIN C20 [get_ports {hdmi_d1[1]}]
#set_property PACKAGE_PIN B19 [get_ports {hdmi_d2[1]}]
#set_property PACKAGE_PIN H16 [get_ports {hdmi_clk[1]}]


#set_clock_groups -name first -asynchronous -group [get_clocks -of_objects [get_pins fm_hdmi_i/clk_wiz_1/inst/plle2_adv_inst/CLKOUT1]] -group [get_clocks phy_rxc]
#set_clock_groups -name second -asynchronous -group [get_clocks -of_objects [get_pins clk_main/inst/mmcm_adv_inst/CLKOUT2]] -group [get_clocks -of_objects [get_pins fm_hdmi_i/clk_wiz_1/inst/plle2_adv_inst/CLKOUT1]]

