# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/sources_1/bd/fm_hdmi/ip/fm_hdmi_fir_compiler_0_5/fm_hdmi_fir_compiler_0_5.xci
# IP: The module: 'fm_hdmi_fir_compiler_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_fir_compiler_0_5/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_hdmi_fir_compiler_0_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_fir_compiler_0_5/fm_hdmi_fir_compiler_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_hdmi_fir_compiler_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/sources_1/bd/fm_hdmi/ip/fm_hdmi_fir_compiler_0_5/fm_hdmi_fir_compiler_0_5.xci
# IP: The module: 'fm_hdmi_fir_compiler_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_fir_compiler_0_5/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_hdmi_fir_compiler_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_fir_compiler_0_5/fm_hdmi_fir_compiler_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_hdmi_fir_compiler_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
