# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/eth_loopback.xdc

# XDC: new/111.xdc

# Block Designs: bd/fm_hdmi/fm_hdmi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi || ORIG_REF_NAME==fm_hdmi} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_1/fm_hdmi_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_clk_wiz_0_1 || ORIG_REF_NAME==fm_hdmi_clk_wiz_0_1} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_2/fm_hdmi_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_clk_wiz_0_2 || ORIG_REF_NAME==fm_hdmi_clk_wiz_0_2} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_udp_mpx_framer_0_0/fm_hdmi_udp_mpx_framer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_udp_mpx_framer_0_0 || ORIG_REF_NAME==fm_hdmi_udp_mpx_framer_0_0} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_fifo_generator_0_0/fm_hdmi_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_fifo_generator_0_0 || ORIG_REF_NAME==fm_hdmi_fifo_generator_0_0} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_udp_phy_shell_0_0/fm_hdmi_udp_phy_shell_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_udp_phy_shell_0_0 || ORIG_REF_NAME==fm_hdmi_udp_phy_shell_0_0} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_udp_tx_start_ctrl_0_0/fm_hdmi_udp_tx_start_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_udp_tx_start_ctrl_0_0 || ORIG_REF_NAME==fm_hdmi_udp_tx_start_ctrl_0_0} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_util_vector_logic_0_1/fm_hdmi_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_util_vector_logic_0_1 || ORIG_REF_NAME==fm_hdmi_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_udp_top_0_0/fm_hdmi_udp_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_udp_top_0_0 || ORIG_REF_NAME==fm_hdmi_udp_top_0_0} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_LTC_2208_0_0/fm_hdmi_LTC_2208_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_LTC_2208_0_0 || ORIG_REF_NAME==fm_hdmi_LTC_2208_0_0} -quiet] -quiet

# IP: bd/fm_hdmi/ip/fm_hdmi_stations_to_packet_0_0/fm_hdmi_stations_to_packet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_hdmi_stations_to_packet_0_0 || ORIG_REF_NAME==fm_hdmi_stations_to_packet_0_0} -quiet] -quiet

# XDC: /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/fm_hdmi_ooc.xdc
