# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.cache/wt [current_project]
set_property parent.project_path /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/reting/Desktop/Github/Radio_FM/fir_384_140_190.coe
add_files /home/reting/Desktop/Github/Radio_FM/fir_decim2_hex.coe
add_files /home/reting/Desktop/Github/Radio_FM/bpf_lr23_53_96.coe
add_files /home/reting/Desktop/Github/Radio_FM/bpf_pilot19_96.coe
add_files /home/reting/Desktop/Github/Radio_FM/0_15k_96.coe
read_verilog -library xil_defaultlib /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/sources_1/new/top.v
add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/sources_1/bd/fm_hdmi/fm_hdmi.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_1/fm_hdmi_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_1/fm_hdmi_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_1/fm_hdmi_clk_wiz_0_1_late.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_1/fm_hdmi_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_2/fm_hdmi_clk_wiz_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_2/fm_hdmi_clk_wiz_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_2/fm_hdmi_clk_wiz_0_2_late.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_clk_wiz_0_2/fm_hdmi_clk_wiz_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_fifo_generator_0_0/fm_hdmi_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/ip/fm_hdmi_fifo_generator_0_0/fm_hdmi_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/fm_hdmi_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_0/packer_udp2_inst_0.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_0/ip/packer_udp2_inst_0_fifo_generator_audio_0/packer_udp2_inst_0_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_0/ip/packer_udp2_inst_0_fifo_generator_audio_0/packer_udp2_inst_0_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_0/ip/packer_udp2_inst_0_fifo_generator_audio_0/packer_udp2_inst_0_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_0/packer_udp2_inst_0_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_1/packer_udp2_inst_1.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_1/ip/packer_udp2_inst_1_fifo_generator_audio_0/packer_udp2_inst_1_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_1/ip/packer_udp2_inst_1_fifo_generator_audio_0/packer_udp2_inst_1_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_1/ip/packer_udp2_inst_1_fifo_generator_audio_0/packer_udp2_inst_1_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_1/packer_udp2_inst_1_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/packer_udp2_inst_2.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/ip/packer_udp2_inst_2_fifo_generator_audio_0/packer_udp2_inst_2_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_2/packer_udp2_inst_2_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_3/packer_udp2_inst_3.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_3/ip/packer_udp2_inst_3_fifo_generator_audio_0/packer_udp2_inst_3_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_3/ip/packer_udp2_inst_3_fifo_generator_audio_0/packer_udp2_inst_3_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_3/ip/packer_udp2_inst_3_fifo_generator_audio_0/packer_udp2_inst_3_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_3/packer_udp2_inst_3_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_4/packer_udp2_inst_4.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_4/ip/packer_udp2_inst_4_fifo_generator_audio_0/packer_udp2_inst_4_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_4/ip/packer_udp2_inst_4_fifo_generator_audio_0/packer_udp2_inst_4_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_4/ip/packer_udp2_inst_4_fifo_generator_audio_0/packer_udp2_inst_4_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_4/packer_udp2_inst_4_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_5/packer_udp2_inst_5.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_5/ip/packer_udp2_inst_5_fifo_generator_audio_0/packer_udp2_inst_5_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_5/ip/packer_udp2_inst_5_fifo_generator_audio_0/packer_udp2_inst_5_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_5/ip/packer_udp2_inst_5_fifo_generator_audio_0/packer_udp2_inst_5_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_5/packer_udp2_inst_5_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_6/packer_udp2_inst_6.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_6/ip/packer_udp2_inst_6_fifo_generator_audio_0/packer_udp2_inst_6_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_6/ip/packer_udp2_inst_6_fifo_generator_audio_0/packer_udp2_inst_6_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_6/ip/packer_udp2_inst_6_fifo_generator_audio_0/packer_udp2_inst_6_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_6/packer_udp2_inst_6_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_7/packer_udp2_inst_7.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_7/ip/packer_udp2_inst_7_fifo_generator_audio_0/packer_udp2_inst_7_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_7/ip/packer_udp2_inst_7_fifo_generator_audio_0/packer_udp2_inst_7_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_7/ip/packer_udp2_inst_7_fifo_generator_audio_0/packer_udp2_inst_7_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_7/packer_udp2_inst_7_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_8/packer_udp2_inst_8.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_8/ip/packer_udp2_inst_8_fifo_generator_audio_0/packer_udp2_inst_8_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_8/ip/packer_udp2_inst_8_fifo_generator_audio_0/packer_udp2_inst_8_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_8/ip/packer_udp2_inst_8_fifo_generator_audio_0/packer_udp2_inst_8_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_8/packer_udp2_inst_8_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_9/packer_udp2_inst_9.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_9/ip/packer_udp2_inst_9_fifo_generator_audio_0/packer_udp2_inst_9_fifo_generator_audio_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_9/ip/packer_udp2_inst_9_fifo_generator_audio_0/packer_udp2_inst_9_fifo_generator_audio_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_9/ip/packer_udp2_inst_9_fifo_generator_audio_0/packer_udp2_inst_9_fifo_generator_audio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/packer_udp2_inst_9/packer_udp2_inst_9_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/fm_demod2_inst_0.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_cic_compiler_3_0/fm_demod2_inst_0_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_fir_compiler_0_0/fm_demod2_inst_0_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_fir_compiler_1_0/fm_demod2_inst_0_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_cic_compiler_2_0/fm_demod2_inst_0_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_dec384to192_0/fm_demod2_inst_0_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_cmpy_0_0/fm_demod2_inst_0_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_cordic_1_0/fm_demod2_inst_0_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_cmpy_1_0/fm_demod2_inst_0_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_dds_compiler_0_0/fm_demod2_inst_0_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_vio_0_0/fm_demod2_inst_0_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/ip/fm_demod2_inst_0_vio_0_0/fm_demod2_inst_0_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_0/fm_demod2_inst_0_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/fm_demod2_inst_2.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_cic_compiler_3_0/fm_demod2_inst_2_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_fir_compiler_0_0/fm_demod2_inst_2_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_fir_compiler_1_0/fm_demod2_inst_2_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_cic_compiler_2_0/fm_demod2_inst_2_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_dec384to192_0/fm_demod2_inst_2_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_cmpy_0_0/fm_demod2_inst_2_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_cordic_1_0/fm_demod2_inst_2_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_cmpy_1_0/fm_demod2_inst_2_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_dds_compiler_0_0/fm_demod2_inst_2_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_vio_0_0/fm_demod2_inst_2_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/ip/fm_demod2_inst_2_vio_0_0/fm_demod2_inst_2_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_2/fm_demod2_inst_2_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/fm_demod2_inst_3.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_cic_compiler_3_0/fm_demod2_inst_3_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_fir_compiler_0_0/fm_demod2_inst_3_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_fir_compiler_1_0/fm_demod2_inst_3_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_cic_compiler_2_0/fm_demod2_inst_3_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_dec384to192_0/fm_demod2_inst_3_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_cmpy_0_0/fm_demod2_inst_3_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_cordic_1_0/fm_demod2_inst_3_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_cmpy_1_0/fm_demod2_inst_3_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_dds_compiler_0_0/fm_demod2_inst_3_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_vio_0_0/fm_demod2_inst_3_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/ip/fm_demod2_inst_3_vio_0_0/fm_demod2_inst_3_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_3/fm_demod2_inst_3_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/fm_demod2_inst_4.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_cic_compiler_3_0/fm_demod2_inst_4_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_fir_compiler_0_0/fm_demod2_inst_4_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_fir_compiler_1_0/fm_demod2_inst_4_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_cic_compiler_2_0/fm_demod2_inst_4_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_dec384to192_0/fm_demod2_inst_4_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_cmpy_0_0/fm_demod2_inst_4_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_cordic_1_0/fm_demod2_inst_4_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_cmpy_1_0/fm_demod2_inst_4_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_dds_compiler_0_0/fm_demod2_inst_4_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_vio_0_0/fm_demod2_inst_4_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/ip/fm_demod2_inst_4_vio_0_0/fm_demod2_inst_4_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_4/fm_demod2_inst_4_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/fm_demod2_inst_5.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_cic_compiler_3_0/fm_demod2_inst_5_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_fir_compiler_0_0/fm_demod2_inst_5_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_fir_compiler_1_0/fm_demod2_inst_5_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_cic_compiler_2_0/fm_demod2_inst_5_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_dec384to192_0/fm_demod2_inst_5_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_cmpy_0_0/fm_demod2_inst_5_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_cordic_1_0/fm_demod2_inst_5_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_cmpy_1_0/fm_demod2_inst_5_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_dds_compiler_0_0/fm_demod2_inst_5_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_vio_0_0/fm_demod2_inst_5_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/ip/fm_demod2_inst_5_vio_0_0/fm_demod2_inst_5_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_5/fm_demod2_inst_5_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/fm_demod2_inst_6.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_cic_compiler_3_0/fm_demod2_inst_6_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_fir_compiler_0_0/fm_demod2_inst_6_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_fir_compiler_1_0/fm_demod2_inst_6_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_cic_compiler_2_0/fm_demod2_inst_6_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_dec384to192_0/fm_demod2_inst_6_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_cmpy_0_0/fm_demod2_inst_6_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_cordic_1_0/fm_demod2_inst_6_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_cmpy_1_0/fm_demod2_inst_6_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_dds_compiler_0_0/fm_demod2_inst_6_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_vio_0_0/fm_demod2_inst_6_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/ip/fm_demod2_inst_6_vio_0_0/fm_demod2_inst_6_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_6/fm_demod2_inst_6_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/fm_demod2_inst_7.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_cic_compiler_3_0/fm_demod2_inst_7_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_fir_compiler_0_0/fm_demod2_inst_7_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_fir_compiler_1_0/fm_demod2_inst_7_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_cic_compiler_2_0/fm_demod2_inst_7_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_dec384to192_0/fm_demod2_inst_7_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_cmpy_0_0/fm_demod2_inst_7_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_cordic_1_0/fm_demod2_inst_7_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_cmpy_1_0/fm_demod2_inst_7_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_dds_compiler_0_0/fm_demod2_inst_7_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_vio_0_0/fm_demod2_inst_7_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/ip/fm_demod2_inst_7_vio_0_0/fm_demod2_inst_7_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_7/fm_demod2_inst_7_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/fm_demod2_inst_8.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_cic_compiler_3_0/fm_demod2_inst_8_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_fir_compiler_0_0/fm_demod2_inst_8_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_fir_compiler_1_0/fm_demod2_inst_8_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_cic_compiler_2_0/fm_demod2_inst_8_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_dec384to192_0/fm_demod2_inst_8_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_cmpy_0_0/fm_demod2_inst_8_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_cordic_1_0/fm_demod2_inst_8_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_cmpy_1_0/fm_demod2_inst_8_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_dds_compiler_0_0/fm_demod2_inst_8_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_vio_0_0/fm_demod2_inst_8_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/ip/fm_demod2_inst_8_vio_0_0/fm_demod2_inst_8_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_8/fm_demod2_inst_8_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/fm_demod2_inst_9.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cic_compiler_3_0/fm_demod2_inst_9_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_fir_compiler_0_0/fm_demod2_inst_9_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_fir_compiler_1_0/fm_demod2_inst_9_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cic_compiler_2_0/fm_demod2_inst_9_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_dec384to192_0/fm_demod2_inst_9_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cmpy_0_0/fm_demod2_inst_9_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cordic_1_0/fm_demod2_inst_9_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_cmpy_1_0/fm_demod2_inst_9_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_dds_compiler_0_0/fm_demod2_inst_9_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_vio_0_0/fm_demod2_inst_9_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/ip/fm_demod2_inst_9_vio_0_0/fm_demod2_inst_9_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_9/fm_demod2_inst_9_ooc.xdc]

add_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/fm_demod2_inst_10.bd
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_cic_compiler_3_0/fm_demod2_inst_10_cic_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_fir_compiler_0_0/fm_demod2_inst_10_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_fir_compiler_1_0/fm_demod2_inst_10_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_cic_compiler_2_0/fm_demod2_inst_10_cic_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_dec384to192_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_dec384to192_0/fm_demod2_inst_10_dec384to192_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_cmpy_0_0/fm_demod2_inst_10_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_cordic_1_0/fm_demod2_inst_10_cordic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_cmpy_1_0/fm_demod2_inst_10_cmpy_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_dds_compiler_0_0/fm_demod2_inst_10_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_vio_0_0/fm_demod2_inst_10_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/ip/fm_demod2_inst_10_vio_0_0/fm_demod2_inst_10_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/bd/fm_hdmi/bd/fm_demod2_inst_10/fm_demod2_inst_10_ooc.xdc]

read_ip -quiet /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/constrs_1/imports/new/eth_loopback.xdc
set_property used_in_implementation false [get_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/constrs_1/imports/new/eth_loopback.xdc]

read_xdc /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/constrs_1/new/111.xdc
set_property used_in_implementation false [get_files /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/constrs_1/new/111.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/reting/Desktop/Github/Radio_FM/ltc2208_max5885.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7z020clg400-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
